---
- name: Download Cloudflare GPG key
  ansible.builtin.get_url:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    dest: /usr/share/keyrings/cloudflare-main.gpg
    mode: '0644'

- name: Add Cloudflare repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/cloudflared.list
    content: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main\n"
    mode: '0644'

- name: Create cloudflared user
  ansible.builtin.user:
    name: cloudflared
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: Set cloudflared default options
  ansible.builtin.copy:
    src: files/cloudflared
    dest: /etc/default/cloudflared
    owner: cloudflared
    group: cloudflared
    mode: '0644'

- name: Ensure cloudflared systemd service file is in place
  ansible.builtin.copy:
    src: files/cloudflared.service
    dest: /etc/systemd/system/cloudflared.service
    owner: root
    group: root
    mode: '0644'

- name: Install cloudflared
  ansible.builtin.apt:
    name: cloudflared
    update_cache: true

- name: Enable cloudflared service
  ansible.builtin.systemd:
    name: cloudflared.service
    enabled: true
